services:

  database:
    image: docker.io/library/postgres:16.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1
      interval: 5s
      start_period: 2s

  migrate:
    image: docker.io/migrate/migrate:v4.16.2
    volumes:
      - ./migrations:/var/lib/migrations
    entrypoint:
      - /migrate
      - -source=file:///var/lib/migrations
      - -database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}?sslmode=disable
    command:
      - up
    depends_on:
      database:
        condition: service_healthy

  admin:
    image: docker.io/sosedoff/pgweb:0.14.1
    environment:
      PGWEB_DATABASE_URL: ${PGWEB_DATABASE_URL}
    ports:
      - ${PGWEB_PORT}:8081
    depends_on:
      database:
        condition: service_healthy
